---
roles:
  - name: m13tlabs.nvm
    version: v1.1.0
collections:
  - name: community.general
  # Required by the molecule docker driver for testing only - not needed to
  # use this role.
  - name: community.docker
  - name: ansible.posix
