---
- name: Rollout .dotfiles
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: ~/
    mode: u+x,g+x,o+x
  with_items:
    - terminal/.vimrc

- name: Ensure vim is installed 
  ansible.builtin.package:
    name: vim
    state: present
  become: true
  when:
    - ansible_facts['os_family'] != 'Darwin'

- name: Rollout bash profile
  ansible.builtin.template:
    src: terminal/profile.j2
    dest: ~/{{ item }}
    mode: u+x,g+x,o+x
  with_items:
    - .bashrc
    - .profile
